//! The README's "Code generator" section, compiled and run.
//!
//! CORELIB_PLAN §9 requires every API name a README states to match the code as
//! it stands today, and §9.5 requires the generator section to show the one-shot
//! `encode()` / `decode()` helpers **and** the streaming `serialize` /
//! `decoder()` path (§6.1.1). The README's section is not a hand-written
//! stand-in: it is the Zig backend's real output for a two-field schema
//!
//!     messages: { point: { payload: { x: {id: 1, type: i32},
//!                                     y: {id: 2, type: i32} } } }
//!
//! trimmed to the parts that schema uses (doc comments, array/string machinery
//! and the location stack elided) and reflowed by `zig fmt`.
//!
//! This file holds that same code and exercises it, so the documented surface
//! is compiled against the corelib rather than asserted in prose. `readme_tests`
//! checks, line by line, that what the README prints is what stands here.

// --- README: generated code (mirrored verbatim) ------------------------------

// Code generated by sofabgen; DO NOT EDIT.
const std = @import("std");
const sofab = @import("sofab");

/// The corelib baseline plus IncompleteMessage: for a one-shot decode over a
/// whole buffer, a trailing .incomplete means the message was truncated.
pub const DecodeError = sofab.Error || error{IncompleteMessage};

/// A 2D point.
pub const Point = struct {
    x: i32 = 0,
    y: i32 = 0,

    /// Worst-case encoded size of this message, derived from the schema.
    pub const MAX_SIZE: usize = 12;

    /// Streaming out: write this value's fields into any OStream.
    pub fn serialize(self: *const Point, os: *sofab.OStream) sofab.Error!void {
        if (self.x != 0) try os.writeSigned(1, self.x);
        if (self.y != 0) try os.writeSigned(2, self.y);
    }

    /// One-shot: `serialize` into a scratch buffer drained by a growing sink.
    pub fn encode(self: *const Point, alloc: std.mem.Allocator) (sofab.Error || std.mem.Allocator.Error)![]u8 {
        var sink: _EncodeSink = .{ .alloc = alloc };
        var scratch: [512]u8 = undefined;
        var os = sofab.OStream.initFlush(&scratch, 0, &sink, _EncodeSink.push);
        try self.serialize(&os);
        _ = os.flush();
        if (sink.failed) return error.OutOfMemory;
        return sink.list.toOwnedSlice(alloc);
    }

    /// One-shot: the generated visitor driven over one whole buffer. Zero-copy —
    /// string/blob fields would borrow from `data`; truncated input fails with
    /// error.IncompleteMessage, malformed input with error.InvalidMessage.
    pub fn decode(alloc: std.mem.Allocator, data: []const u8) DecodeError!Point {
        var m: Point = .{};
        var v: _dec_Point = .{ .m = &m, .alloc = alloc };
        const st = try sofab.decode(data, &v);
        if (v.inv) return error.InvalidMessage;
        if (st == .incomplete) return error.IncompleteMessage;
        return m;
    }

    /// Incremental decoder: hold one and feed the message as bytes arrive.
    /// Unlike decode(), this path COPIES every string and blob into `alloc`.
    pub const Decoder = struct {
        is: sofab.IStream = sofab.IStream.init(),
        v: _dec_Point,

        /// Feed the next chunk, of any size. `.complete` means the bytes ended
        /// on a field boundary, `.incomplete` mid-field — neither answers
        /// whether the MESSAGE is done.
        pub fn feed(self: *Decoder, chunk: []const u8) DecodeError!sofab.Status {
            const st = try self.is.feed(chunk, &self.v);
            if (self.v.inv) return error.InvalidMessage;
            return st;
        }

        /// The outcome for everything fed so far, without feeding more.
        pub fn status(self: *const Decoder) sofab.Status {
            return self.is.status();
        }

        /// Declare end-of-input: a stream that ended mid-field fails here.
        pub fn finish(self: *const Decoder) DecodeError!void {
            if (self.is.status() == .incomplete) return error.IncompleteMessage;
        }
    };

    /// Streaming in: an incremental decoder filling `out`.
    pub fn decoder(out: *Point, alloc: std.mem.Allocator) Decoder {
        return .{ .v = .{ .m = out, .alloc = alloc, .own = true } };
    }
};

/// The `deserialize` half of §6.1.1: the per-field hook the corelib's decoder
/// calls. A schema with arrays, strings or nested sequences also gets
/// `arrayBegin`, a payload reassembler and a `sequenceBegin`/`sequenceEnd`
/// location stack here.
const _dec_Point = struct {
    m: *Point,
    alloc: std.mem.Allocator,
    own: bool = false, // copy payloads instead of borrowing (streaming path)
    inv: bool = false, // a value outside its schema bound -> INVALID

    pub fn signed(self: *_dec_Point, id: sofab.Id, value: sofab.Signed) void {
        switch (id) {
            1 => {
                if (value < -2147483648 or value > 2147483647) {
                    self.inv = true;
                    return;
                }
                self.m.x = @intCast(value);
            },
            2 => {
                if (value < -2147483648 or value > 2147483647) {
                    self.inv = true;
                    return;
                }
                self.m.y = @intCast(value);
            },
            else => {},
        }
    }
};

/// Flush sink behind encode(): drains the OStream scratch into a byte list.
const _EncodeSink = struct {
    alloc: std.mem.Allocator,
    list: std.ArrayList(u8) = .empty,
    failed: bool = false,
    fn push(ctx: ?*anyopaque, data: []const u8) void {
        const self: *_EncodeSink = @ptrCast(@alignCast(ctx.?));
        self.list.appendSlice(self.alloc, data) catch {
            self.failed = true;
        };
    }
};

// --- README: usage (mirrored verbatim, inside a test) ------------------------

test "README: the generated one-shot and streaming paths" {
    // The generated layer allocates; the corelib still does not. An arena
    // frees the whole message at once.
    var arena = std.heap.ArenaAllocator.init(std.heap.page_allocator);
    defer arena.deinit();
    const alloc = arena.allocator();

    // --- one-shot: encode()/decode(), thin wrappers over the streaming pair ---
    const wire = try (Point{ .x = 3, .y = 4 }).encode(alloc);
    const got = try Point.decode(alloc, wire); // got.x == 3, got.y == 4

    // --- streaming out: an output buffer smaller than the message + a sink ---
    const Sink = struct {
        buf: [Point.MAX_SIZE]u8 = undefined,
        len: usize = 0,
        fn push(ctx: ?*anyopaque, chunk: []const u8) void {
            const self: *@This() = @ptrCast(@alignCast(ctx.?));
            @memcpy(self.buf[self.len..][0..chunk.len], chunk);
            self.len += chunk.len;
        }
    };
    var sink: Sink = .{};
    var scratch: [4]u8 = undefined; // well under MAX_SIZE: the sink drains it
    var os = sofab.OStream.initFlush(&scratch, 0, &sink, Sink.push);
    try (Point{ .x = 3, .y = 4 }).serialize(&os);
    _ = os.flush(); // sink.buf[0..sink.len] is the same message

    // --- streaming in: feed the message in chunks of any size ---------------
    var out: Point = .{};
    var dec = Point.decoder(&out, alloc);
    var st = try dec.feed(wire[0..1]); // .incomplete — ended mid-field
    try std.testing.expectEqual(sofab.Status.incomplete, st);
    st = try dec.feed(wire[1..]); // .complete — ended on a field boundary
    try dec.finish(); // end-of-input: a trailing .incomplete fails here

    // --- what the README's comments claim ------------------------------------
    try std.testing.expectEqual(@as(i32, 3), got.x);
    try std.testing.expectEqual(@as(i32, 4), got.y);
    try std.testing.expectEqualSlices(u8, wire, sink.buf[0..sink.len]);
    try std.testing.expectEqual(sofab.Status.complete, st);
    try std.testing.expectEqual(sofab.Status.complete, dec.status());
    try std.testing.expectEqual(Point{ .x = 3, .y = 4 }, out);
}

test "README: the one-shot helpers report truncation and malformed input" {
    const alloc = std.testing.allocator;
    const wire = try (Point{ .x = 3, .y = 4 }).encode(alloc);
    defer alloc.free(wire);

    // A message cut mid-field is INCOMPLETE, never a silently short decode.
    try std.testing.expectError(error.IncompleteMessage, Point.decode(alloc, wire[0 .. wire.len - 1]));
    // Malformed bytes are INVALID and stay INVALID (a header for a wire type
    // that does not exist).
    try std.testing.expectError(error.InvalidMessage, Point.decode(alloc, &[_]u8{0x0F}));

    // The streaming path separates the two the same way.
    var out: Point = .{};
    var dec = Point.decoder(&out, alloc);
    try std.testing.expectEqual(sofab.Status.incomplete, try dec.feed(wire[0 .. wire.len - 1]));
    try std.testing.expectError(error.IncompleteMessage, dec.finish());
}

test "README: MAX_SIZE bounds this schema's worst case" {
    const alloc = std.testing.allocator;
    const wire = try (Point{ .x = std.math.minInt(i32), .y = std.math.minInt(i32) }).encode(alloc);
    defer alloc.free(wire);
    try std.testing.expect(wire.len <= Point.MAX_SIZE);
}
