//! Conformance against the **shared** cross-language test vectors.
//!
//! The architecture spec mandates that every `corelib-<lang>` consume
//! `assets/test_vectors.json` — generated by `corelib-c-cpp`, the source of
//! truth — rather than a divergent hand-maintained copy. This suite embeds that
//! file at build time and, for every vector, checks the spec's scenarios:
//!
//! 1. **encode** — replay `fields[]`, assert output matches `serialized.hex`.
//! 2. **chunked-encode** — re-encode through tiny 1/3/7-byte flush buffers
//!    (exercising the buffer-full → flush → resume path) and assert the
//!    streamed-out bytes still match `serialized.hex`.
//! 3. **decode** — feed the official hex, assert the recovered fields match.
//! 4. **chunked-decode** — feed the same bytes one byte at a time, assert
//!    identical events.
//! 5. **skip** — for vectors carrying `skip_ids`, a receiver that ignores those
//!    ids (skipping a `sequence_begin` skips its whole sub-tree) must still
//!    recover every other field, whole and chunked.
//!
//! Roundtrip (encode → decode) falls out of running (1) and (3) on every
//! vector.
//!
//! This build has every wire type and the 64-bit value width compiled in, so
//! all shared vectors are representable and run (`requires` tags matter only to
//! feature-reduced builds and are ignored here, per the vector README).

const std = @import("std");
const sofab = @import("sofab");
const common = @import("common.zig");

const Event = common.Event;
const Id = sofab.Id;

/// The shared vectors, embedded verbatim from the asset copy.
const vectors_json = @embedFile("test_vectors");

// --- JSON helpers -------------------------------------------------------------

fn get(v: std.json.Value, key: []const u8) ?std.json.Value {
    return v.object.get(key);
}

/// Unsigned integers span the full u64 range; values above `i64` max arrive
/// from std.json as `.number_string`.
fn asU64(v: std.json.Value) u64 {
    return switch (v) {
        .integer => |i| @intCast(i),
        .number_string => |s| std.fmt.parseInt(u64, s, 10) catch @panic("bad u64 in vectors"),
        else => @panic("expected unsigned number"),
    };
}

fn asI64(v: std.json.Value) i64 {
    return switch (v) {
        .integer => |i| i,
        .number_string => |s| std.fmt.parseInt(i64, s, 10) catch @panic("bad i64 in vectors"),
        else => @panic("expected signed number"),
    };
}

/// A finite float as a JSON number, or ±infinity as the strings `inf`/`-inf`.
fn asF64(v: std.json.Value) f64 {
    return switch (v) {
        .float => |f| f,
        .integer => |i| @floatFromInt(i),
        .number_string => |s| std.fmt.parseFloat(f64, s) catch @panic("bad float in vectors"),
        .string => |s| if (std.mem.eql(u8, s, "inf"))
            std.math.inf(f64)
        else if (std.mem.eql(u8, s, "-inf"))
            -std.math.inf(f64)
        else
            @panic("unexpected float string"),
        else => @panic("expected float"),
    };
}

fn fieldId(f: std.json.Value) Id {
    const v = get(f, "id") orelse return 0;
    return @intCast(asU64(v));
}

// --- encode --------------------------------------------------------------------

/// Replay a vector's `fields[]` into an encoder.
fn writeFields(os: *sofab.OStream, arena: std.mem.Allocator, fields: []const std.json.Value) !void {
    for (fields) |f| {
        const op = get(f, "op").?.string;
        const id = fieldId(f);
        if (std.mem.eql(u8, op, "unsigned")) {
            try os.writeUnsigned(id, asU64(get(f, "value").?));
        } else if (std.mem.eql(u8, op, "signed")) {
            try os.writeSigned(id, asI64(get(f, "value").?));
        } else if (std.mem.eql(u8, op, "boolean")) {
            try os.writeBoolean(id, get(f, "value").?.bool);
        } else if (std.mem.eql(u8, op, "fp32")) {
            try os.writeFp32(id, @floatCast(asF64(get(f, "value").?)));
        } else if (std.mem.eql(u8, op, "fp64")) {
            try os.writeFp64(id, asF64(get(f, "value").?));
        } else if (std.mem.eql(u8, op, "string")) {
            try os.writeString(id, get(f, "value").?.string);
        } else if (std.mem.eql(u8, op, "blob")) {
            try os.writeBlob(id, common.hexToBytes(arena, get(f, "value_hex").?.string));
        } else if (std.mem.eql(u8, op, "array")) {
            try writeArray(os, arena, id, f);
        } else if (std.mem.eql(u8, op, "sequence_begin")) {
            try os.writeSequenceBegin(id);
        } else if (std.mem.eql(u8, op, "sequence_end")) {
            try os.writeSequenceEnd();
        } else {
            @panic("unsupported op in vectors");
        }
    }
}

fn intSlice(comptime T: type, arena: std.mem.Allocator, vals: []const std.json.Value) []T {
    const out = arena.alloc(T, vals.len) catch @panic("oom");
    for (vals, out) |v, *o| {
        o.* = if (@typeInfo(T).int.signedness == .unsigned)
            @intCast(asU64(v))
        else
            @intCast(asI64(v));
    }
    return out;
}

fn writeArray(os: *sofab.OStream, arena: std.mem.Allocator, id: Id, f: std.json.Value) !void {
    const et = get(f, "element_type").?.string;
    const vals = get(f, "values").?.array.items;
    // The declared element width affects only the API-side storage, never the
    // wire bytes — replay each vector at its declared width anyway.
    inline for (.{ u8, u16, u32, u64 }) |T| {
        if (std.mem.eql(u8, et, @typeName(T))) {
            return os.writeArrayUnsigned(id, intSlice(T, arena, vals));
        }
    }
    inline for (.{ i8, i16, i32, i64 }) |T| {
        if (std.mem.eql(u8, et, @typeName(T))) {
            return os.writeArraySigned(id, intSlice(T, arena, vals));
        }
    }
    if (std.mem.eql(u8, et, "fp32")) {
        const out = arena.alloc(f32, vals.len) catch @panic("oom");
        for (vals, out) |v, *o| o.* = @floatCast(asF64(v));
        return os.writeArrayFp32(id, out);
    }
    if (std.mem.eql(u8, et, "fp64")) {
        const out = arena.alloc(f64, vals.len) catch @panic("oom");
        for (vals, out) |v, *o| o.* = asF64(v);
        return os.writeArrayFp64(id, out);
    }
    @panic("unsupported element_type in vectors");
}

/// Encode `fields[]` into a single buffer at `offset`, returning the message
/// bytes (without the reserved framing prefix).
fn encodeFields(arena: std.mem.Allocator, fields: []const std.json.Value, offset: usize) ![]const u8 {
    const buf = arena.alloc(u8, 8192) catch @panic("oom");
    var os = sofab.OStream.initOffset(buf, offset);
    try writeFields(&os, arena, fields);
    return buf[offset..os.bytesUsed()];
}

/// Byte sink for the chunked-encode scenario: collects flushed chunks.
const Collector = struct {
    data: [8192]u8 = undefined,
    len: usize = 0,

    fn push(ctx: ?*anyopaque, chunk: []const u8) void {
        const self: *Collector = @ptrCast(@alignCast(ctx.?));
        @memcpy(self.data[self.len..][0..chunk.len], chunk);
        self.len += chunk.len;
    }
};

/// Encode `fields[]` through a tiny `buf_size`-byte buffer with a flush sink,
/// so the encoder repeatedly fills, flushes, and resumes.
fn chunkedEncode(arena: std.mem.Allocator, fields: []const std.json.Value, buf_size: usize) ![]const u8 {
    var scratch: [8]u8 = undefined;
    var out: Collector = .{};
    var os = sofab.OStream.initFlush(scratch[0..buf_size], 0, &out, Collector.push);
    try writeFields(&os, arena, fields);
    _ = os.flush();
    const copy = arena.alloc(u8, out.len) catch @panic("oom");
    @memcpy(copy, out.data[0..out.len]);
    return copy;
}

// --- expected decode events -----------------------------------------------------

fn arrayKind(et: []const u8) sofab.ArrayKind {
    return switch (et[0]) {
        'u' => .unsigned,
        'i' => .signed,
        'f' => .fixlen,
        else => @panic("unknown element_type"),
    };
}

/// Append the decoder events for a single `fields[]` entry.
fn pushFieldEvents(ev: *std.ArrayList(Event), arena: std.mem.Allocator, f: std.json.Value) void {
    const op = get(f, "op").?.string;
    const id = fieldId(f);
    const e: Event = blk: {
        if (std.mem.eql(u8, op, "unsigned")) {
            break :blk .{ .unsigned = .{ .id = id, .value = asU64(get(f, "value").?) } };
        } else if (std.mem.eql(u8, op, "boolean")) {
            // Booleans decode as plain unsigned 0/1.
            break :blk .{ .unsigned = .{ .id = id, .value = @intFromBool(get(f, "value").?.bool) } };
        } else if (std.mem.eql(u8, op, "signed")) {
            break :blk .{ .signed = .{ .id = id, .value = asI64(get(f, "value").?) } };
        } else if (std.mem.eql(u8, op, "fp32")) {
            break :blk .{ .fp32 = .{ .id = id, .bits = @bitCast(@as(f32, @floatCast(asF64(get(f, "value").?)))) } };
        } else if (std.mem.eql(u8, op, "fp64")) {
            break :blk .{ .fp64 = .{ .id = id, .bits = @bitCast(asF64(get(f, "value").?)) } };
        } else if (std.mem.eql(u8, op, "string")) {
            break :blk .{ .str = .{ .id = id, .data = get(f, "value").?.string } };
        } else if (std.mem.eql(u8, op, "blob")) {
            break :blk .{ .blob = .{ .id = id, .data = common.hexToBytes(arena, get(f, "value_hex").?.string) } };
        } else if (std.mem.eql(u8, op, "sequence_begin")) {
            break :blk .{ .sequence_begin = .{ .id = id } };
        } else if (std.mem.eql(u8, op, "sequence_end")) {
            break :blk .sequence_end;
        } else if (std.mem.eql(u8, op, "array")) {
            const et = get(f, "element_type").?.string;
            const vals = get(f, "values").?.array.items;
            ev.append(arena, .{ .array_begin = .{ .id = id, .kind = arrayKind(et), .count = vals.len } }) catch @panic("oom");
            for (vals) |v| {
                ev.append(arena, switch (arrayKind(et)) {
                    .unsigned => .{ .unsigned = .{ .id = id, .value = asU64(v) } },
                    .signed => .{ .signed = .{ .id = id, .value = asI64(v) } },
                    .fixlen => if (std.mem.eql(u8, et, "fp32"))
                        .{ .fp32 = .{ .id = id, .bits = @bitCast(@as(f32, @floatCast(asF64(v)))) } }
                    else
                        .{ .fp64 = .{ .id = id, .bits = @bitCast(asF64(v)) } },
                }) catch @panic("oom");
            }
            return;
        } else {
            @panic("unsupported op in vectors");
        }
    };
    ev.append(arena, e) catch @panic("oom");
}

/// The events a correct decoder must emit for one vector's `fields[]`.
fn expectedEvents(arena: std.mem.Allocator, fields: []const std.json.Value) []const Event {
    var ev: std.ArrayList(Event) = .empty;
    for (fields) |f| pushFieldEvents(&ev, arena, f);
    return ev.items;
}

/// The events a receiver must observe for `fields[]` when it ignores
/// `skip_ids`: skipped scalars/arrays are dropped; a skipped `sequence_begin`
/// drops the entire nested sequence.
fn expectedEventsWithSkip(arena: std.mem.Allocator, fields: []const std.json.Value, skip: []const Id) []const Event {
    var ev: std.ArrayList(Event) = .empty;
    var depth: u32 = 0;
    var skip_until: ?u32 = null;
    for (fields) |f| {
        const op = get(f, "op").?.string;
        const id = fieldId(f);
        if (std.mem.eql(u8, op, "sequence_begin")) {
            if (skip_until == null and std.mem.indexOfScalar(Id, skip, id) != null) {
                skip_until = depth;
            } else if (skip_until == null) {
                ev.append(arena, .{ .sequence_begin = .{ .id = id } }) catch @panic("oom");
            }
            depth += 1;
        } else if (std.mem.eql(u8, op, "sequence_end")) {
            depth -= 1;
            if (skip_until) |d| {
                if (d == depth) skip_until = null;
            } else {
                ev.append(arena, .sequence_end) catch @panic("oom");
            }
        } else if (skip_until == null and std.mem.indexOfScalar(Id, skip, id) == null) {
            pushFieldEvents(&ev, arena, f);
        }
    }
    return ev.items;
}

// --- decode ----------------------------------------------------------------------

fn decodeAll(arena: std.mem.Allocator, bytes: []const u8) ![]const Event {
    var rec = common.Recorder.init(arena);
    try sofab.decode(bytes, &rec);
    return rec.events.items;
}

fn decodeOneByteAtATime(arena: std.mem.Allocator, bytes: []const u8) ![]const Event {
    var rec = common.Recorder.init(arena);
    var is = sofab.IStream.init();
    for (bytes) |b| try is.feed(&.{b}, &rec);
    try is.finish();
    return rec.events.items;
}

// --- the suite ---------------------------------------------------------------------

fn parseVectors(arena: std.mem.Allocator) []const std.json.Value {
    const doc = std.json.parseFromSliceLeaky(std.json.Value, arena, vectors_json, .{}) catch
        @panic("failed to parse test_vectors.json");
    if (!std.mem.eql(u8, doc.object.get("format").?.string, "sofabuffers-test-vectors"))
        @panic("unexpected vector file format");
    if (doc.object.get("version").?.integer != 1) @panic("unexpected vector file version");
    return doc.object.get("vectors").?.array.items;
}

test "shared vectors are present and carry capability tags" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const vectors = parseVectors(arena_state.allocator());
    try std.testing.expect(vectors.len > 0);
    var tagged: usize = 0;
    for (vectors) |v| {
        if (get(v, "requires") != null) tagged += 1;
    }
    try std.testing.expect(tagged > 0);
}

test "all shared vectors conform (encode, chunked-encode, decode, chunked-decode)" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const vectors = parseVectors(arena);

    var ran: usize = 0;
    for (vectors) |vec| {
        ran += 1;
        const name = get(vec, "name").?.string;
        errdefer std.debug.print("vector [{s}] failed\n", .{name});

        const offset: usize = if (get(vec, "offset")) |o| @intCast(asU64(o)) else 0;
        const fields = get(vec, "fields").?.array.items;
        const expected_bytes = common.hexToBytes(arena, get(get(vec, "serialized").?, "hex").?.string);

        // 1. Vector encode: replay fields, bytes must match the ground truth.
        const encoded = try encodeFields(arena, fields, offset);
        try std.testing.expectEqualSlices(u8, expected_bytes, encoded);

        // 2. Chunked encode: stream out through tiny flush buffers.
        for ([_]usize{ 1, 3, 7 }) |bs| {
            try std.testing.expectEqualSlices(u8, expected_bytes, try chunkedEncode(arena, fields, bs));
        }

        // 3. Vector decode: feed the official bytes, recovered fields must match.
        const want = expectedEvents(arena, fields);
        try common.expectEventsEqual(want, try decodeAll(arena, expected_bytes));

        // 4. Chunked decode: one byte at a time yields identical events.
        try common.expectEventsEqual(want, try decodeOneByteAtATime(arena, expected_bytes));
    }

    try std.testing.expect(ran > 0);
}

test "skip_ids vectors conform (whole and chunked)" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const vectors = parseVectors(arena);

    var seen: usize = 0;
    for (vectors) |vec| {
        const skip_json = get(vec, "skip_ids") orelse continue;
        seen += 1;
        const name = get(vec, "name").?.string;
        errdefer std.debug.print("skip vector [{s}] failed\n", .{name});

        const skip = arena.alloc(Id, skip_json.array.items.len) catch @panic("oom");
        for (skip_json.array.items, skip) |v, *s| s.* = @intCast(asU64(v));

        const fields = get(vec, "fields").?.array.items;
        const bytes = common.hexToBytes(arena, get(get(vec, "serialized").?, "hex").?.string);

        const want = expectedEventsWithSkip(arena, fields, skip);
        // Sanity: the skip set must actually drop something.
        try std.testing.expect(want.len < expectedEvents(arena, fields).len);

        var rec = common.SkipRecorder.init(arena, skip);
        try sofab.decode(bytes, &rec);
        try common.expectEventsEqual(want, rec.events());

        var rec2 = common.SkipRecorder.init(arena, skip);
        var is = sofab.IStream.init();
        for (bytes) |b| try is.feed(&.{b}, &rec2);
        try is.finish();
        try common.expectEventsEqual(want, rec2.events());
    }

    // Every shared skip vector is supported in this build.
    try std.testing.expect(seen >= 8);
}
