//! Conformance against the **shared** cross-language test vectors.
//!
//! The architecture spec mandates that every `corelib-<lang>` consume
//! `assets/test_vectors.json` — generated by `corelib-c-cpp`, the source of
//! truth — rather than a divergent hand-maintained copy. This suite embeds that
//! file at build time and, for every vector, checks the spec's scenarios:
//!
//! 1. **encode** — replay `fields[]`, assert output matches `serialized.hex`.
//! 2. **chunked-encode** — re-encode through tiny 1/3/7-byte flush buffers
//!    (exercising the buffer-full → flush → resume path) and assert the
//!    streamed-out bytes still match `serialized.hex`.
//! 3. **decode** — feed the official hex, assert the recovered fields match.
//! 4. **chunked-decode** — feed the same bytes one byte at a time, assert
//!    identical events.
//! 5. **skip** — for vectors carrying `skip_ids`, a receiver that ignores those
//!    ids (skipping a `sequence_begin` skips its whole sub-tree) must still
//!    recover every other field, whole and chunked.
//! 6. **decoder-side skip** — the same vectors again, once per callback kind
//!    their skipped fields use, through a visitor that leaves exactly that
//!    callback undeclared. Scenario 5 filters events a receiver was handed;
//!    this one makes the *decoder* walk the skipped field's bytes and discard
//!    them, which is what `skip_ids` describes and the only way this port's
//!    duck-typed visitor can decline anything (`@hasDecl`, and the absence of
//!    `sequenceBegin` for a whole sub-sequence). Whole and chunked, so a skip
//!    is exercised across chunk boundaries too.
//!
//! Roundtrip (encode → decode) falls out of running (1) and (3) on every
//! vector.
//!
//! **Capability gating.** A vector's optional `requires` list names the library
//! features it needs. This build has every wire type and the 64-bit value width
//! compiled in — there is no `SOFAB_DISABLE_*` equivalent here — so every tag
//! resolves to "supported" and no vector is gated out, which is exactly what
//! the vector README prescribes for a port that cannot compile features out.
//! The tags are still *resolved* rather than ignored (`Capability`): an
//! unrecognised one stops the suite instead of quietly running a vector this
//! build may not represent, and a port that later grows a feature switch flips
//! one arm and gets the matrix graded per configuration.
//!
//! **Nothing is silently narrowed.** Every number the loader takes out of the
//! JSON — vector ids, values, array elements, skip ids, offsets — is
//! range-checked before it is stored (`narrowU`/`narrowI`, `fieldId`),
//! and every fixed-capacity buffer the suite encodes into is checked against
//! the vector that is about to use it (`buffer_bytes`). A vector that outgrows
//! this harness therefore fails loudly rather than testing less than it claims
//! — the failure mode the shared C runner's fixed `MAXSKIP` had, where an
//! over-long `skip_ids` list was truncated and the extra ids got *read*.
//!
//! **The run says what it covered.** Each scenario prints the number of vectors
//! it ran, the number gated out, and the number of checks it made.

const std = @import("std");
const sofab = @import("sofab");
const common = @import("common.zig");

const Event = common.Event;
const Id = sofab.Id;

/// The shared vectors, embedded verbatim from the asset copy.
///
/// **Which column this suite asserts:** `serialized.hex` — the dense,
/// primitive-layer ground truth, where every sequence in the op list carries its
/// frame. That is the only column a corelib *can* assert: this repo has no
/// message layer, so it has no schema, no declared defaults and therefore no way
/// to decide that a sequence field equals its default.
///
/// The sibling `serialized_sparse.hex` column — the same message with an
/// all-default sequence *field* omitted (MESSAGE_SPEC §2) — is deliberately
/// **not** read here. It is produced and checked one layer up, by the
/// generator's per-language conformance drivers
/// (`tests/conformance/zig/check_vectors.py` in sofa-buffers/generator), which
/// own the schema that says what "default" means. What this corelib owes that
/// layer is the `writeSequenceEnd` / `writeSequenceEndKeep` pair those drivers
/// build on, covered by the lazy-framing unit tests in `src/ostream.zig`.
const vectors_json = @embedFile("test_vectors");

// --- JSON helpers -------------------------------------------------------------

fn get(v: std.json.Value, key: []const u8) ?std.json.Value {
    return v.object.get(key);
}

/// Unsigned integers span the full u64 range; values above `i64` max arrive
/// from std.json as `.number_string`.
fn asU64(v: std.json.Value) u64 {
    return switch (v) {
        // Negative here would wrap to a huge unsigned in a release build — the
        // same silent misread `narrowU` exists to prevent, one layer earlier.
        .integer => |i| blk: {
            if (i < 0) {
                std.debug.print("vector value {d} is negative where an unsigned is expected\n", .{i});
                @panic("test_vectors.json holds a value this loader would misread");
            }
            break :blk @intCast(i);
        },
        .number_string => |s| std.fmt.parseInt(u64, s, 10) catch @panic("bad u64 in vectors"),
        else => @panic("expected unsigned number"),
    };
}

fn asI64(v: std.json.Value) i64 {
    return switch (v) {
        .integer => |i| i,
        .number_string => |s| std.fmt.parseInt(i64, s, 10) catch @panic("bad i64 in vectors"),
        else => @panic("expected signed number"),
    };
}

/// A finite float as a JSON number, or ±infinity as the strings `inf`/`-inf`.
fn asF64(v: std.json.Value) f64 {
    return switch (v) {
        .float => |f| f,
        .integer => |i| @floatFromInt(i),
        .number_string => |s| std.fmt.parseFloat(f64, s) catch @panic("bad float in vectors"),
        .string => |s| if (std.mem.eql(u8, s, "inf"))
            std.math.inf(f64)
        else if (std.mem.eql(u8, s, "-inf"))
            -std.math.inf(f64)
        else
            @panic("unexpected float string"),
        else => @panic("expected float"),
    };
}

/// A vector's `u64` narrowed to `T`, **refusing** rather than truncating.
///
/// `@intCast` would be a safety panic in Debug and silent corruption in
/// ReleaseFast; the shared vectors now carry ids up to 100001 and 130-element
/// arrays, so the loader states the bound it is enforcing instead of assuming
/// one.
fn narrowU(comptime T: type, v: u64) T {
    if (v > std.math.maxInt(T)) {
        std.debug.print("vector value {d} does not fit {s}\n", .{ v, @typeName(T) });
        @panic("test_vectors.json holds a value this loader would truncate");
    }
    return @intCast(v);
}

/// The signed counterpart of `narrowU`.
fn narrowI(comptime T: type, v: i64) T {
    if (v < std.math.minInt(T) or v > std.math.maxInt(T)) {
        std.debug.print("vector value {d} does not fit {s}\n", .{ v, @typeName(T) });
        @panic("test_vectors.json holds a value this loader would truncate");
    }
    return @intCast(v);
}

fn fieldId(f: std.json.Value) Id {
    const v = get(f, "id") orelse return 0;
    return narrowU(Id, asU64(v));
}

// --- capability gating (`requires`) -------------------------------------------

/// The optional library features a vector can ask for. The tag set is the
/// shared vector README's table; `dynamic_arrays` is deliberately absent, as it
/// tags the `sequence_growth` block only (that block is run by
/// `sequence_growth_tests.zig`, which owns its gating).
const Capability = enum {
    /// fp32/fp64/string/blob, or a fixed-length array.
    fixlen,
    /// any array field.
    array,
    /// a nested sequence.
    sequence,
    /// a 64-bit float (implies `fixlen`).
    fp64,
    /// a value, element or id outside the 32-bit range.
    int64,

    /// Resolve a tag from the asset, refusing an unknown one: silently ignoring
    /// it would run a vector against a build that may not represent it.
    fn parse(tag: []const u8) Capability {
        return std.meta.stringToEnum(Capability, tag) orelse {
            std.debug.print("unknown `requires` capability tag: {s}\n", .{tag});
            @panic("teach this suite the capability tag rather than ignoring it");
        };
    }

    /// Whether *this* build can represent the capability. Every arm is `true`:
    /// this port compiles the whole wire format in unconditionally. The switch
    /// is exhaustive on purpose — a build option that removes a feature flips
    /// its arm, and the skip matrix then grades itself per configuration
    /// instead of being dropped whole.
    fn supported(self: Capability) bool {
        return switch (self) {
            .fixlen, .array, .sequence, .fp64, .int64 => true,
        };
    }
};

/// True when a vector asks for something this build cannot represent, so it is
/// reported as gated out rather than run (or silently dropped).
fn gatedOut(vec: std.json.Value) bool {
    const reqs = get(vec, "requires") orelse return false;
    for (reqs.array.items) |r| {
        if (!Capability.parse(r.string).supported()) return true;
    }
    return false;
}

// --- run accounting -----------------------------------------------------------

/// Capacity of every fixed buffer this suite encodes into. Checked against each
/// vector before it is used, so a longer vector fails loudly here rather than
/// overrunning a collector in a release build.
const buffer_bytes: usize = 8192;

fn assertFits(name: []const u8, len: usize) void {
    if (len > buffer_bytes) {
        std.debug.print("vector [{s}] is {d} bytes, buffers hold {d}\n", .{ name, len, buffer_bytes });
        @panic("raise `buffer_bytes` — never run a vector through a buffer too small for it");
    }
}

/// What a scenario covered, printed at the end of its test so a CI log states
/// how much of the shared suite actually executed (the acceptance criterion
/// upstream reports as "vectors / checks").
const Coverage = struct {
    vectors: usize = 0,
    gated: usize = 0,
    checks: usize = 0,

    fn check(self: *Coverage) void {
        self.checks += 1;
    }

    fn report(self: Coverage, scenario: []const u8, detail: []const u8) void {
        // Leading newline: the test runner leaves the cursor after
        // "N/M <test name>...", so the report starts on a line of its own.
        std.debug.print(
            "\n[vectors] {s}: {d} vectors run, {d} gated out by `requires`, {d} checks{s}\n",
            .{ scenario, self.vectors, self.gated, self.checks, detail },
        );
    }
};

// --- encode --------------------------------------------------------------------

/// Replay a vector's `fields[]` into an encoder.
fn writeFields(os: *sofab.OStream, arena: std.mem.Allocator, fields: []const std.json.Value) !void {
    for (fields) |f| {
        const op = get(f, "op").?.string;
        const id = fieldId(f);
        if (std.mem.eql(u8, op, "unsigned")) {
            try os.writeUnsigned(id, asU64(get(f, "value").?));
        } else if (std.mem.eql(u8, op, "signed")) {
            try os.writeSigned(id, asI64(get(f, "value").?));
        } else if (std.mem.eql(u8, op, "boolean")) {
            try os.writeBoolean(id, get(f, "value").?.bool);
        } else if (std.mem.eql(u8, op, "fp32")) {
            try os.writeFp32(id, @floatCast(asF64(get(f, "value").?)));
        } else if (std.mem.eql(u8, op, "fp64")) {
            try os.writeFp64(id, asF64(get(f, "value").?));
        } else if (std.mem.eql(u8, op, "string")) {
            try os.writeString(id, get(f, "value").?.string);
        } else if (std.mem.eql(u8, op, "blob")) {
            try os.writeBlob(id, common.hexToBytes(arena, get(f, "value_hex").?.string));
        } else if (std.mem.eql(u8, op, "array")) {
            try writeArray(os, arena, id, f);
        } else if (std.mem.eql(u8, op, "sequence_begin")) {
            try os.writeSequenceBeginLazy(id);
        } else if (std.mem.eql(u8, op, "sequence_end")) {
            // The vectors' op list is replayed against the **dense**
            // `serialized` hex, which always carries the frame — including the
            // three empty-sequence vectors. So the replay closes with
            // `writeSequenceEndKeep`: `writeSequenceEnd` would drop a
            // contentless frame and those vectors would encode to nothing.
            // (The sparse-canonical form, where the field-position frame *is*
            // dropped, is the `serialized_sparse` hex — a generated-code
            // concern, not a raw-encoder replay one.)
            try os.writeSequenceEndKeep();
        } else {
            @panic("unsupported op in vectors");
        }
    }
}

fn intSlice(comptime T: type, arena: std.mem.Allocator, vals: []const std.json.Value) []T {
    const out = arena.alloc(T, vals.len) catch @panic("oom");
    for (vals, out) |v, *o| {
        o.* = if (@typeInfo(T).int.signedness == .unsigned)
            narrowU(T, asU64(v))
        else
            narrowI(T, asI64(v));
    }
    return out;
}

fn writeArray(os: *sofab.OStream, arena: std.mem.Allocator, id: Id, f: std.json.Value) !void {
    const et = get(f, "element_type").?.string;
    const vals = get(f, "values").?.array.items;
    // The declared element width affects only the API-side storage, never the
    // wire bytes — replay each vector at its declared width anyway.
    inline for (.{ u8, u16, u32, u64 }) |T| {
        if (std.mem.eql(u8, et, @typeName(T))) {
            return os.writeArrayUnsigned(id, intSlice(T, arena, vals));
        }
    }
    inline for (.{ i8, i16, i32, i64 }) |T| {
        if (std.mem.eql(u8, et, @typeName(T))) {
            return os.writeArraySigned(id, intSlice(T, arena, vals));
        }
    }
    if (std.mem.eql(u8, et, "fp32")) {
        const out = arena.alloc(f32, vals.len) catch @panic("oom");
        for (vals, out) |v, *o| o.* = @floatCast(asF64(v));
        return os.writeArrayFp32(id, out);
    }
    if (std.mem.eql(u8, et, "fp64")) {
        const out = arena.alloc(f64, vals.len) catch @panic("oom");
        for (vals, out) |v, *o| o.* = asF64(v);
        return os.writeArrayFp64(id, out);
    }
    @panic("unsupported element_type in vectors");
}

/// Encode `fields[]` into a single buffer at `offset`, returning the message
/// bytes (without the reserved framing prefix).
fn encodeFields(arena: std.mem.Allocator, fields: []const std.json.Value, offset: usize) ![]const u8 {
    const buf = arena.alloc(u8, buffer_bytes) catch @panic("oom");
    var os = sofab.OStream.initOffset(buf, offset);
    try writeFields(&os, arena, fields);
    return buf[offset..os.bytesUsed()];
}

/// Encode `fields[]` through a tiny `buf_size`-byte buffer with a flush sink,
/// so the encoder repeatedly fills, flushes, and resumes.
fn chunkedEncode(arena: std.mem.Allocator, fields: []const std.json.Value, buf_size: usize) ![]const u8 {
    var scratch: [8]u8 = undefined;
    var out: common.Collector(buffer_bytes) = .{};
    var os = sofab.OStream.initFlush(scratch[0..buf_size], 0, &out, @TypeOf(out).push);
    try writeFields(&os, arena, fields);
    _ = os.flush();
    const copy = arena.alloc(u8, out.len) catch @panic("oom");
    @memcpy(copy, out.bytes());
    return copy;
}

/// Fill of the framing room a taking sink reserves in every unit; any byte of a
/// reservation the encoder overwrote reads as something else.
const reserved_fill: u8 = 0xEE;

/// Byte sink for the take-and-replace scenario (CORELIB_PLAN §5.1): it *takes*
/// the buffer it was handed — scrubbing it, so a store the encoder makes into
/// it after the return shows up as garbage rather than as the bytes already
/// carried away — and installs the other of two scratch buffers with framing
/// room reserved before returning. The start offset belongs to that
/// installation, so **every** unit begins with its own reservation and the
/// message is what follows the reservations, concatenated.
const TakingCollector = struct {
    a: [16]u8 = @splat(reserved_fill),
    b: [16]u8 = @splat(reserved_fill),
    buf_size: usize,
    reserve: usize,
    data: [buffer_bytes]u8 = undefined,
    len: usize = 0,
    units: usize = 0,
    reservations_intact: bool = true,
    os: *sofab.OStream = undefined,

    fn push(ctx: ?*anyopaque, chunk: []const u8) void {
        const self: *TakingCollector = @ptrCast(@alignCast(ctx.?));
        self.units += 1;
        if (chunk.len < self.reserve) {
            self.reservations_intact = false;
        } else {
            for (chunk[0..self.reserve]) |b| {
                if (b != reserved_fill) self.reservations_intact = false;
            }
            const payload = chunk[self.reserve..];
            if (self.len + payload.len > self.data.len) @panic("taking sink overrun — raise `buffer_bytes`");
            @memcpy(self.data[self.len..][0..payload.len], payload);
            self.len += payload.len;
        }

        const took_a = @intFromPtr(chunk.ptr) == @intFromPtr(&self.a);
        const handed: *[16]u8 = if (took_a) &self.a else &self.b;
        const fresh: *[16]u8 = if (took_a) &self.b else &self.a;
        @memset(handed, 0xAA);
        @memset(fresh, reserved_fill);
        self.os.bufferSet(fresh[0..self.buf_size], self.reserve);
    }
};

/// Encode `fields[]` through a taking sink that hands the encoder a fresh
/// buffer with `reserve` bytes of framing room on every flush, and return the
/// payload behind the reservations.
fn takingEncode(
    arena: std.mem.Allocator,
    fields: []const std.json.Value,
    buf_size: usize,
    reserve: usize,
) ![]const u8 {
    var out: TakingCollector = .{ .buf_size = buf_size, .reserve = reserve };
    var os = sofab.OStream.initFlush(out.a[0..buf_size], reserve, &out, TakingCollector.push);
    out.os = &os;
    try writeFields(&os, arena, fields);
    _ = os.flush();
    try std.testing.expect(out.reservations_intact);
    const copy = arena.alloc(u8, out.len) catch @panic("oom");
    @memcpy(copy, out.data[0..out.len]);
    return copy;
}

// --- expected decode events -----------------------------------------------------

fn arrayKind(et: []const u8) sofab.ArrayKind {
    if (std.mem.eql(u8, et, "fp32")) return .fp32;
    if (std.mem.eql(u8, et, "fp64")) return .fp64;
    return switch (et[0]) {
        'u' => .unsigned,
        'i' => .signed,
        else => @panic("unknown element_type"),
    };
}

/// Append the decoder events for a single `fields[]` entry.
fn pushFieldEvents(ev: *std.ArrayList(Event), arena: std.mem.Allocator, f: std.json.Value) void {
    const op = get(f, "op").?.string;
    const id = fieldId(f);
    const e: Event = blk: {
        if (std.mem.eql(u8, op, "unsigned")) {
            break :blk .{ .unsigned = .{ .id = id, .value = asU64(get(f, "value").?) } };
        } else if (std.mem.eql(u8, op, "boolean")) {
            // Booleans decode as plain unsigned 0/1.
            break :blk .{ .unsigned = .{ .id = id, .value = @intFromBool(get(f, "value").?.bool) } };
        } else if (std.mem.eql(u8, op, "signed")) {
            break :blk .{ .signed = .{ .id = id, .value = asI64(get(f, "value").?) } };
        } else if (std.mem.eql(u8, op, "fp32")) {
            break :blk .{ .fp32 = .{ .id = id, .bits = @bitCast(@as(f32, @floatCast(asF64(get(f, "value").?)))) } };
        } else if (std.mem.eql(u8, op, "fp64")) {
            break :blk .{ .fp64 = .{ .id = id, .bits = @bitCast(asF64(get(f, "value").?)) } };
        } else if (std.mem.eql(u8, op, "string")) {
            break :blk .{ .str = .{ .id = id, .data = get(f, "value").?.string } };
        } else if (std.mem.eql(u8, op, "blob")) {
            break :blk .{ .blob = .{ .id = id, .data = common.hexToBytes(arena, get(f, "value_hex").?.string) } };
        } else if (std.mem.eql(u8, op, "sequence_begin")) {
            break :blk .{ .sequence_begin = .{ .id = id } };
        } else if (std.mem.eql(u8, op, "sequence_end")) {
            break :blk .sequence_end;
        } else if (std.mem.eql(u8, op, "array")) {
            const et = get(f, "element_type").?.string;
            const vals = get(f, "values").?.array.items;
            ev.append(arena, .{ .array_begin = .{ .id = id, .kind = arrayKind(et), .count = vals.len } }) catch @panic("oom");
            for (vals) |v| {
                ev.append(arena, switch (arrayKind(et)) {
                    .unsigned => .{ .unsigned = .{ .id = id, .value = asU64(v) } },
                    .signed => .{ .signed = .{ .id = id, .value = asI64(v) } },
                    .fp32 => .{ .fp32 = .{ .id = id, .bits = @bitCast(@as(f32, @floatCast(asF64(v)))) } },
                    .fp64 => .{ .fp64 = .{ .id = id, .bits = @bitCast(asF64(v)) } },
                }) catch @panic("oom");
            }
            return;
        } else {
            @panic("unsupported op in vectors");
        }
    };
    ev.append(arena, e) catch @panic("oom");
}

/// The events a correct decoder must emit for one vector's `fields[]`.
fn expectedEvents(arena: std.mem.Allocator, fields: []const std.json.Value) []const Event {
    var ev: std.ArrayList(Event) = .empty;
    for (fields) |f| pushFieldEvents(&ev, arena, f);
    return ev.items;
}

/// The events a receiver must observe for `fields[]` when it ignores
/// `skip_ids`: skipped scalars/arrays are dropped; a skipped `sequence_begin`
/// drops the entire nested sequence.
fn expectedEventsWithSkip(arena: std.mem.Allocator, fields: []const std.json.Value, skip: []const Id) []const Event {
    var ev: std.ArrayList(Event) = .empty;
    var depth: u32 = 0;
    var skip_until: ?u32 = null;
    for (fields) |f| {
        const op = get(f, "op").?.string;
        const id = fieldId(f);
        if (std.mem.eql(u8, op, "sequence_begin")) {
            if (skip_until == null and std.mem.indexOfScalar(Id, skip, id) != null) {
                skip_until = depth;
            } else if (skip_until == null) {
                ev.append(arena, .{ .sequence_begin = .{ .id = id } }) catch @panic("oom");
            }
            depth += 1;
        } else if (std.mem.eql(u8, op, "sequence_end")) {
            depth -= 1;
            if (skip_until) |d| {
                if (d == depth) skip_until = null;
            } else {
                ev.append(arena, .sequence_end) catch @panic("oom");
            }
        } else if (skip_until == null and std.mem.indexOfScalar(Id, skip, id) == null) {
            pushFieldEvents(&ev, arena, f);
        }
    }
    return ev.items;
}

/// The callback kinds the fields named by `skip` are delivered through — i.e.
/// the callbacks a receiver has to leave undeclared for this port's decoder to
/// walk and discard exactly those fields.
///
/// An `array` contributes both `arrayBegin` and its element kind, because the
/// two halves of an array field arrive through different callbacks and either
/// can be declined on its own. A skipped `sequence_begin` contributes
/// `sequence` and nothing else: its contents are not declined one by one, the
/// whole scope is.
fn declinedCallbacks(fields: []const std.json.Value, skip: []const Id) std.EnumSet(common.Callback) {
    var set: std.EnumSet(common.Callback) = .initEmpty();
    var depth: u32 = 0;
    var skip_until: ?u32 = null;
    for (fields) |f| {
        const op = get(f, "op").?.string;
        const id = fieldId(f);
        if (std.mem.eql(u8, op, "sequence_begin")) {
            if (skip_until == null and std.mem.indexOfScalar(Id, skip, id) != null) {
                set.insert(.sequence);
                skip_until = depth;
            }
            depth += 1;
            continue;
        }
        if (std.mem.eql(u8, op, "sequence_end")) {
            depth -= 1;
            if (skip_until) |d| {
                if (d == depth) skip_until = null;
            }
            continue;
        }
        if (skip_until != null or std.mem.indexOfScalar(Id, skip, id) == null) continue;
        if (std.mem.eql(u8, op, "unsigned") or std.mem.eql(u8, op, "boolean")) {
            set.insert(.unsigned);
        } else if (std.mem.eql(u8, op, "signed")) {
            set.insert(.signed);
        } else if (std.mem.eql(u8, op, "fp32")) {
            set.insert(.fp32);
        } else if (std.mem.eql(u8, op, "fp64")) {
            set.insert(.fp64);
        } else if (std.mem.eql(u8, op, "string")) {
            set.insert(.string);
        } else if (std.mem.eql(u8, op, "blob")) {
            set.insert(.blob);
        } else if (std.mem.eql(u8, op, "array")) {
            set.insert(.array);
            set.insert(switch (arrayKind(get(f, "element_type").?.string)) {
                .unsigned => .unsigned,
                .signed => .signed,
                .fp32 => .fp32,
                .fp64 => .fp64,
            });
        } else {
            @panic("unsupported op in vectors");
        }
    }
    return set;
}

/// The events a receiver that declares every callback **but** `omit` must
/// observe for `fields[]`: everything the missing callback would have carried
/// is gone — at every nesting level, and for array elements as well as scalar
/// fields — and everything else still arrives, in order and with its exact
/// value. A missing `arrayBegin` drops only the array header; the elements keep
/// coming through the scalar callbacks. A missing `sequenceBegin` is the whole
/// sub-tree, which is what `expectedEventsTopLevelOnly` already describes.
fn expectedEventsWithout(
    arena: std.mem.Allocator,
    fields: []const std.json.Value,
    comptime omit: common.Callback,
) []const Event {
    if (omit == .sequence) return expectedEventsTopLevelOnly(arena, fields);
    var ev: std.ArrayList(Event) = .empty;
    for (expectedEvents(arena, fields)) |e| {
        const dropped = switch (e) {
            .unsigned => omit == .unsigned,
            .signed => omit == .signed,
            .fp32 => omit == .fp32,
            .fp64 => omit == .fp64,
            .str => omit == .string,
            .blob => omit == .blob,
            .array_begin => omit == .array,
            .sequence_begin, .sequence_end => false,
        };
        if (!dropped) ev.append(arena, e) catch @panic("oom");
    }
    return ev.items;
}

/// The events a receiver that **cannot descend** must observe for `fields[]`:
/// only the top-level, non-sequence fields. A visitor declaring no
/// `sequenceBegin` is never told a scope was entered, so the decoder consumes
/// and discards every sub-sequence whole (CORELIB_PLAN §5.2/§6) — nothing below
/// depth 0 may reach it, and neither may the frame events themselves.
fn expectedEventsTopLevelOnly(arena: std.mem.Allocator, fields: []const std.json.Value) []const Event {
    var ev: std.ArrayList(Event) = .empty;
    var depth: u32 = 0;
    for (fields) |f| {
        const op = get(f, "op").?.string;
        if (std.mem.eql(u8, op, "sequence_begin")) {
            depth += 1;
        } else if (std.mem.eql(u8, op, "sequence_end")) {
            depth -= 1;
        } else if (depth == 0) {
            pushFieldEvents(&ev, arena, f);
        }
    }
    return ev.items;
}

// --- decode ----------------------------------------------------------------------

fn decodeAll(arena: std.mem.Allocator, bytes: []const u8) ![]const Event {
    var rec = common.Recorder.init(arena);
    try std.testing.expectEqual(sofab.Status.complete, try sofab.decode(bytes, &rec));
    return rec.events.items;
}

fn decodeOneByteAtATime(arena: std.mem.Allocator, bytes: []const u8) ![]const Event {
    var rec = common.Recorder.init(arena);
    var is = sofab.IStream.init();
    var st: sofab.Status = .complete; // a decoder fed nothing sits at a field boundary
    for (bytes) |b| st = try is.feed(&.{b}, &rec);
    try std.testing.expectEqual(sofab.Status.complete, st);
    return rec.events.items;
}

// --- the suite ---------------------------------------------------------------------

fn parseVectors(arena: std.mem.Allocator) []const std.json.Value {
    const doc = std.json.parseFromSliceLeaky(std.json.Value, arena, vectors_json, .{}) catch
        @panic("failed to parse test_vectors.json");
    if (!std.mem.eql(u8, doc.object.get("format").?.string, "sofabuffers-test-vectors"))
        @panic("unexpected vector file format");
    if (doc.object.get("version").?.integer != 1) @panic("unexpected vector file version");
    return doc.object.get("vectors").?.array.items;
}

/// The shared `invalid_utf8` list: `string` payloads no strict encoder may put
/// on the wire and no strict decoder may accept (CORELIB_PLAN §6.4).
fn parseInvalidUtf8(arena: std.mem.Allocator) []const std.json.Value {
    const doc = std.json.parseFromSliceLeaky(std.json.Value, arena, vectors_json, .{}) catch
        @panic("failed to parse test_vectors.json");
    return doc.object.get("invalid_utf8").?.array.items;
}

test "shared vectors are present and carry capability tags" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const vectors = parseVectors(arena_state.allocator());
    // The asset is a verbatim copy of corelib-c-cpp's (CORELIB_PLAN §7.1/§8);
    // the generation that added the skip matrix has 131 vectors. A copy that
    // regressed to an older, smaller file is caught here rather than by a
    // scenario quietly covering less.
    try std.testing.expect(vectors.len >= 131);
    var tagged: usize = 0;
    for (vectors) |v| {
        if (get(v, "requires") != null) tagged += 1;
        // Every tag in the file resolves; an unknown one panics here.
        _ = gatedOut(v);
    }
    try std.testing.expect(tagged > 0);
}

test "all shared vectors conform (encode, chunked-encode, decode, chunked-decode)" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const vectors = parseVectors(arena);

    var cov: Coverage = .{};
    for (vectors) |vec| {
        const name = get(vec, "name").?.string;
        errdefer std.debug.print("vector [{s}] failed\n", .{name});
        if (gatedOut(vec)) {
            cov.gated += 1;
            continue;
        }
        cov.vectors += 1;

        const offset: usize = if (get(vec, "offset")) |o| narrowU(usize, asU64(o)) else 0;
        const fields = get(vec, "fields").?.array.items;
        const expected_bytes = common.hexToBytes(arena, get(get(vec, "serialized").?, "hex").?.string);
        assertFits(name, expected_bytes.len + offset);

        // 1. Vector encode: replay fields, bytes must match the ground truth.
        const encoded = try encodeFields(arena, fields, offset);
        try std.testing.expectEqualSlices(u8, expected_bytes, encoded);
        cov.check();

        // 2. Chunked encode: stream out through tiny flush buffers.
        for ([_]usize{ 1, 3, 7 }) |bs| {
            try std.testing.expectEqualSlices(u8, expected_bytes, try chunkedEncode(arena, fields, bs));
            cov.check();
        }

        // 2b. Take-and-replace encode (§5.1): the sink takes each buffer and
        // installs a replacement with framing room reserved, so every flushed
        // unit carries its own reservation and the payload behind them is the
        // same message.
        for ([_][2]usize{ .{ 2, 1 }, .{ 8, 3 } }) |cfg| {
            try std.testing.expectEqualSlices(
                u8,
                expected_bytes,
                try takingEncode(arena, fields, cfg[0], cfg[1]),
            );
            cov.check();
        }

        // 3. Vector decode: feed the official bytes, recovered fields must match.
        const want = expectedEvents(arena, fields);
        try common.expectEventsEqual(want, try decodeAll(arena, expected_bytes));
        cov.check();

        // 4. Chunked decode: one byte at a time yields identical events.
        try common.expectEventsEqual(want, try decodeOneByteAtATime(arena, expected_bytes));
        cov.check();
    }

    cov.report("encode/decode", "");
    try std.testing.expect(cov.vectors > 0);
}

/// Per-group tallies for the skip scenario, so the run states that the whole
/// skip matrix executed rather than just "some vectors with `skip_ids`".
const SkipGroups = struct {
    matrix_total: usize = 0,
    matrix_run: usize = 0,
    plain_total: usize = 0,
    plain_run: usize = 0,

    fn count(self: *SkipGroups, group: []const u8, was_run: bool) void {
        if (std.mem.eql(u8, group, "skip/matrix")) {
            self.matrix_total += 1;
            if (was_run) self.matrix_run += 1;
        } else if (std.mem.eql(u8, group, "skip")) {
            self.plain_total += 1;
            if (was_run) self.plain_run += 1;
        }
    }
};

test "skip_ids vectors conform (whole and chunked)" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const vectors = parseVectors(arena);

    var cov: Coverage = .{};
    var groups: SkipGroups = .{};
    var longest_skip_list: usize = 0;
    // The decoder-side pass: how many decodes ran through a visitor that
    // declines a callback, and which callbacks were declined at least once.
    var declined_decodes: usize = 0;
    var declined_seen: std.EnumSet(common.Callback) = .initEmpty();
    for (vectors) |vec| {
        const skip_json = get(vec, "skip_ids") orelse continue;
        const name = get(vec, "name").?.string;
        errdefer std.debug.print("skip vector [{s}] failed\n", .{name});
        const runnable = !gatedOut(vec);
        groups.count(get(vec, "group").?.string, runnable);
        if (!runnable) {
            cov.gated += 1;
            continue;
        }
        cov.vectors += 1;

        // The skip set is taken whole: it is sized from the asset, never from a
        // fixed bound, so no id can be dropped off the end and end up *read*.
        const skip = arena.alloc(Id, skip_json.array.items.len) catch @panic("oom");
        for (skip_json.array.items, skip) |v, *sk| sk.* = narrowU(Id, asU64(v));
        longest_skip_list = @max(longest_skip_list, skip.len);

        const fields = get(vec, "fields").?.array.items;
        const bytes = common.hexToBytes(arena, get(get(vec, "serialized").?, "hex").?.string);

        const want = expectedEventsWithSkip(arena, fields, skip);
        // Sanity: the skip set must actually drop something.
        try std.testing.expect(want.len < expectedEvents(arena, fields).len);

        var rec = common.SkipRecorder.init(arena, skip);
        try std.testing.expectEqual(sofab.Status.complete, try sofab.decode(bytes, &rec));
        try common.expectEventsEqual(want, rec.events());
        cov.check();

        var rec2 = common.SkipRecorder.init(arena, skip);
        var is = sofab.IStream.init();
        var st: sofab.Status = .complete; // a decoder fed nothing sits at a field boundary
        for (bytes) |b| st = try is.feed(&.{b}, &rec2);
        try std.testing.expectEqual(sofab.Status.complete, st);
        try common.expectEventsEqual(want, rec2.events());
        cov.check();

        // …and the same vector through the decoder's *own* skip path.
        //
        // The two decodes above put the whole message through a visitor that
        // declares every callback and drops the ids it was told to ignore. That
        // is an event filter: it proves the skipped fields decode, not that
        // anything was skipped — the decoder delivered them. This port has no
        // per-id decline API to express `skip_ids` with (declining is per
        // callback kind, through `@hasDecl`, and per sub-sequence, through the
        // absence of `sequenceBegin`), so the way a receiver here actually
        // refuses the fields `skip_ids` names is to not declare their callback.
        //
        // So decode the vector once more per callback kind its skipped fields
        // use, through a visitor missing exactly that callback. Now the decoder
        // has to walk each of those fields itself — past its length word, its
        // element count, its element width, its end marker — and every field
        // that follows is an anchor that catches a walk which ended on the
        // wrong byte. Whole and one byte at a time, so a skip is also exercised
        // across chunk boundaries.
        const declined = declinedCallbacks(fields, skip);
        try std.testing.expect(declined.count() > 0);
        declined_seen.setUnion(declined);
        inline for (comptime std.enums.values(common.Callback)) |cb| {
            if (declined.contains(cb)) {
                const want_cb = expectedEventsWithout(arena, fields, cb);
                const Visitor = common.Declining(cb);

                var dec = Visitor.init(arena);
                try std.testing.expectEqual(sofab.Status.complete, try sofab.decode(bytes, &dec));
                try common.expectEventsEqual(want_cb, dec.events());
                cov.check();

                var dec2 = Visitor.init(arena);
                var is2 = sofab.IStream.init();
                var st_cb: sofab.Status = .complete; // a decoder fed nothing sits at a field boundary
                for (bytes) |b| st_cb = try is2.feed(&.{b}, &dec2);
                try std.testing.expectEqual(sofab.Status.complete, st_cb);
                try common.expectEventsEqual(want_cb, dec2.events());
                cov.check();

                declined_decodes += 2;
            }
        }
    }

    var detail_buf: [192]u8 = undefined;
    cov.report("skip + chunked skip", std.fmt.bufPrint(
        &detail_buf,
        " (skip/matrix {d}/{d}, skip {d}/{d}, longest skip_ids {d}, {d} decoder-skip decodes over {d}/{d} callback kinds)",
        .{
            groups.matrix_run,     groups.matrix_total,
            groups.plain_run,      groups.plain_total,
            longest_skip_list,     declined_decodes,
            declined_seen.count(), std.enums.values(common.Callback).len,
        },
    ) catch unreachable);

    // The generation of the asset that added the skip matrix carries 36
    // `skip/matrix` and 16 `skip` vectors, and 58 vectors with `skip_ids` in
    // total. Asserting the floors keeps a stale copy of the file — or a loader
    // that stopped seeing part of it — from passing quietly.
    try std.testing.expect(groups.matrix_total >= 36);
    try std.testing.expect(groups.plain_total >= 16);
    try std.testing.expect(cov.vectors + cov.gated >= 58);
    // Nothing in this build is gated out, so everything with `skip_ids` ran.
    try std.testing.expectEqual(@as(usize, 0), cov.gated);
    // …and the longest list in the asset (9 ids) arrived whole.
    try std.testing.expect(longest_skip_list >= 9);
    // The matrix declines every skippable construct in turn, so every callback
    // kind must have been left undeclared at least once — otherwise the
    // decoder-side pass silently covers less than the file offers.
    try std.testing.expectEqual(std.enums.values(common.Callback).len, declined_seen.count());
    try std.testing.expect(declined_decodes >= 2 * cov.vectors);
}

test "every vector auto-skips its sub-sequences for a visitor that cannot descend" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();
    const vectors = parseVectors(arena);

    // Vectors whose events a non-descending visitor must *not* see in full —
    // the ones that actually carry a sequence. Counted so this test cannot
    // silently degrade into "all vectors are flat anyway".
    var cov: Coverage = .{};
    var nested: usize = 0;
    for (vectors) |vec| {
        const name = get(vec, "name").?.string;
        errdefer std.debug.print("auto-skip vector [{s}] failed\n", .{name});
        if (gatedOut(vec)) {
            cov.gated += 1;
            continue;
        }
        cov.vectors += 1;

        const fields = get(vec, "fields").?.array.items;
        const bytes = common.hexToBytes(arena, get(get(vec, "serialized").?, "hex").?.string);
        const want = expectedEventsTopLevelOnly(arena, fields);
        if (want.len != expectedEvents(arena, fields).len) nested += 1;

        var rec = common.FlatRecorder.init(arena);
        try std.testing.expectEqual(sofab.Status.complete, try sofab.decode(bytes, &rec));
        try common.expectEventsEqual(want, rec.events());
        cov.check();

        // Chunk-independence: the same events one byte at a time.
        var rec2 = common.FlatRecorder.init(arena);
        var is = sofab.IStream.init();
        var st: sofab.Status = .complete; // a decoder fed nothing sits at a field boundary
        for (bytes) |b| st = try is.feed(&.{b}, &rec2);
        try std.testing.expectEqual(sofab.Status.complete, st);
        try common.expectEventsEqual(want, rec2.events());
        cov.check();
    }

    cov.report("auto-skip (non-descending visitor)", "");
    try std.testing.expect(nested >= 8);
}

test "invalid_utf8 vectors: every string writer honours the encode outcome (§6.4)" {
    var arena_state = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena_state.deinit();
    const arena = arena_state.allocator();

    var cov: Coverage = .{};
    for (parseInvalidUtf8(arena)) |vec| {
        const name = get(vec, "name").?.string;
        errdefer std.debug.print("invalid_utf8 vector [{s}] failed\n", .{name});
        // `invalid_argument` is the only encode outcome this list carries; a new
        // one would need its own handling rather than being silently ignored.
        try std.testing.expectEqualStrings("invalid_argument", get(vec, "encode_outcome").?.string);

        const id = narrowU(Id, asU64(get(vec, "id").?));
        const payload = common.hexToBytes(arena, get(vec, "string_hex").?.string);
        const expected = common.hexToBytes(arena, get(vec, "serialized_hex").?.string);
        cov.vectors += 1;

        var buf: [64]u8 = undefined;
        if (expected.len > buf.len) @panic("invalid_utf8 vector outgrew the encode buffer — raise it");

        // Both spellings of "write a string field" must agree: `writeString`
        // and the generic `writeFixlen(.string)` reach the same wire shape, so
        // the same policy has to gate both.
        for ([_]bool{ false, true }) |via_fixlen| {
            var os = sofab.OStream.init(&buf);
            const res = if (via_fixlen)
                os.writeFixlen(id, payload, .string)
            else
                os.writeString(id, payload);

            if (comptime sofab.STRICT_UTF8) {
                try std.testing.expectError(sofab.Error.InvalidArgument, res);
                // Refused whole: not one byte of the field reaches the wire.
                try std.testing.expectEqual(@as(usize, 0), os.bytesUsed());
            } else {
                // A documented non-strict build writes the bytes verbatim, and
                // what it writes is exactly the vector's serialization.
                try res;
                try std.testing.expectEqualSlices(u8, expected, buf[0..os.bytesUsed()]);
            }
            cov.check();
        }

        // `blob` is opaque bytes and is never validated, in either build: the
        // same payload under the blob subtype always goes out.
        var os_blob = sofab.OStream.init(&buf);
        try os_blob.writeBlob(id, payload);
        try std.testing.expect(os_blob.bytesUsed() > payload.len);
        cov.check();
    }

    cov.report("invalid_utf8 encode", "");
    // The list is part of the shared asset; an empty run would mean this suite
    // silently stopped covering the encode side.
    try std.testing.expect(cov.vectors >= 8);
}
